apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.8.7/manifests/install.yaml

patches:
  - path: notifications-controller.yaml