apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.10.7/manifests/install.yaml

patches:
  - path: dex-server.yaml
  - path: notifications-controller.yaml
  - path: argocd-cm.yaml
  - path: argocd-server.yaml
  - path: argocd-application-controller.yaml
  - path: argocd-applicationset-controller.yaml
  - path: argocd-repo-server.yaml
  - path: argocd-redis.yaml
  - path: argocd-tls-certs-cm.yaml.tmpl
